version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - Ambossmann
    assignees:
      - Ambossmann

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - Ambossmann
    assignees:
      - Ambossmann
      
